FROM node:latest

LABEL maintainer="Teddy Fontaine"
LABEL org.opencontainers.image.source https://github.com/tfSheol/meet-nalia-interview-test-full-stack

WORKDIR /app

COPY dist/ .
COPY package.json .
COPY package-lock.json .
COPY node_modules/ ./node_modules

ENTRYPOINT [ "node", "main.js" ]